name: swagger_dart_code_generator

version: 3.0.1

homepage: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
repository: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
issue_tracker: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

description: Have you been turned into a problem with writing code for Http
  requests? This package can help. It has all of the Http and model codegen
  functionality you have been looking for.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.2
  code_builder: ^4.10.1
  collection: ^1.19.1
  dart_style: ^3.1.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  markdown: ">=5.0.0 <8.0.0"
  path: ^1.9.1
  recase: ^4.1.0
  universal_io: ^2.2.2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^6.0.0
  remove_from_coverage: ^2.0.0
  test: ^1.26.2
